# ─── Gradle performance ───────────────────────────────────────────────────────
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

# ─── Android ──────────────────────────────────────────────────────────────────
android.useAndroidX=true
android.nonTransitiveRClass=true

# ─── Kotlin ───────────────────────────────────────────────────────────────────
kotlin.code.style=official

# ─── Kora Charts — metadata publicada a Maven Central ─────────────────────────
GROUP=com.rl04x.koracharts
VERSION_NAME=0.1.0-alpha02

POM_URL=https://github.com/raul04x/rl04x-kora-charts
POM_SCM_URL=https://github.com/raul04x/rl04x-kora-charts
POM_SCM_CONNECTION=scm:git:git://github.com/raul04x/rl04x-kora-charts.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com:raul04x/rl04x-kora-charts.git
POM_LICENCE_NAME=Apache License 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=raul04x
POM_DEVELOPER_NAME=Raul Oviedo & Kora Charts Contributors

org.gradle.tooling.parallel=true
